# Generated by Django 4.0.3 on 2022-03-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discipline', models.CharField(choices=[('PT', 'Physical Therapist'), ('OT', 'Occupational Therapist'), ('SP', 'Speech Therapist')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.CharField(max_length=150)),
                ('clinician', models.ManyToManyField(to='main_app.clinician')),
            ],
            options={
                'ordering': ['lastname'],
            },
        ),
    ]
