# Generated by Django 4.0.3 on 2022-04-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_patient_zip_alter_clinician_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='clinician',
            field=models.ManyToManyField(null=True, to='main_app.clinician'),
        ),
    ]
